### ISSUE TITLE
Link proxy

### ISSUE THREAD

**Issue by draco1544** [in03/Resolve-Proxy-Encoder#6]
This is not a real issue, is juste a question : how I can juste use the script for link proxy ? I don't have any knowledges in da vinci scripting

**Comment by in03** [comment]
Hey! Thanks for the interest @draco1544, and sorry for the mess - I'm still kinda fiddling around with this and will probably end up dropping the proxy-centric thing and refactoring it into more of a general encoding/filter pipeline.

As far as linking proxies goes, there's a few prerequisites. **Assuming you use Windows:**
1. Make sure you're running Resolve studio. No scripting in free. 
2. In your Resolve general settings, set `Use/Enable Scripting`(? can't remember what it's called) to `local`.
2. Make sure you have a version of python 3.6 installed. If you open Resolve, go to the toolbar and click Workspace > Console > Python 3, it'll warn you if it's not installed.
3. Then go Workspace > Documentation > Developer. It'll open a file browser. Open `Scripting`, then `README.txt`. Follow the official instructions there to get scripts running. It can be a bit fiddly, but you only have to do it once (per computer...)
4. In the proxy_encoder folder for this repo, open `config.yml`. Set `proxy_path_root` to wherever you usually store your proxies. If you store them in all different places, just give it an existing starting point, like `C:\`.
5. To actually run the script conveniently, you can run it directly using a Streamdeck or a keyboard combo with Autohotkey, but the simplest way to do it without any extras is just create an empty text file next to `link_proxies.py` and paste the following into it ```py -3.6 "%~dp0/link_proxies.py"
pause```. Then you can right click it, create a shortcut, and put that shortcut wherever you like. On the taskbar or desktop maybe. Any issues and you should get an error message in the console window.

**Just know**, the script will recursively search the folder you select for any files with a matching name! If you have multiple possible matches, there's no knowing you'll link to the right file. Also, if you choose a really big folder, like `C:/` it could search for a very long time. Be specific if you can.

Hope it all works out! :) Let me know if you have any dramas.
Some of those instructions may be a little off in their names and stuff, I just went off memory, no access to Resolve atm.
